import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'title-sm': ['Inter'],
                'display-lg': ['Inter'],
                'display-md': ['Inter'],
                'body-md': ['Inter'],
                'body-sm': ['Inter'],
                'headline-lg': ['Inter'],
                'headline-md': ['Inter'],
                'headline-sm': ['Inter'],
                'data-mono': ['JetBrains Mono'],
                'code-sm': ['JetBrains Mono'],
                'code-md': ['JetBrains Mono'],
                'label-md': ['Inter'],
                'label-form': ['Inter'],
                'label-sm': ['Inter'],
            },
            colors: {
                // ---- Project colors (original keys preserved) ----
                'on-primary-fixed': '#001a41',
                'inverse-surface': '#2e3132',
                'surface-variant': '#e1e3e4',
                'tertiary-fixed-dim': '#312f2b',
                'primary-fixed': '#d8e2ff',
                'on-tertiary': '#ffffff',
                'tertiary-container': '#6d767e',
                secondary: '#465f88',
                error: '#ba1a1a',
                'on-surface': '#191c1d',
                'error-container': '#ffdad6',
                'on-tertiary-fixed': '#371400',
                'primary-fixed-dim': '#adc7ff',
                'on-primary-container': '#0f2a55',
                'inverse-on-surface': '#f0f1f2',
                'on-primary': '#ffffff',
                'on-background': '#191c1d',
                'secondary-container': '#b6d0ff',
                'on-secondary-container': '#3f5881',
                'on-tertiary-fixed-variant': '#53381d',
                'on-secondary': '#ffffff',
                'secondary-fixed': '#d6e3ff',
                'surface-container-low': '#f3f4f5',
                background: '#f8f9fa',
                'surface-container-highest': '#e1e3e4',
                'surface-container-high': '#e7e8e9',
                'outline-variant': '#c1c6d7',
                'on-error-container': '#93000a',
                'inverse-primary': '#adc7ff',
                'surface-dim': '#d9dadb',
                surface: '#f8f9fa',
                outline: '#717786',
                'tertiary-fixed': '#dbe4ed',
                'primary-container': '#0070ea',
                'surface-bright': '#f8f9fa',
                'secondary-fixed-dim': '#aec7f6',
                'surface-container': '#edeeef',
                'on-surface-variant': '#414754',
                'on-primary-fixed-variant': '#004493',
                'on-secondary-fixed-variant': '#2d476f',
                'surface-container-lowest': '#ffffff',
                'on-secondary-fixed': '#001b3d',
                tertiary: '#545d65',
                'on-error': '#ffffff',
                'on-tertiary-container': '#fcfcff',
                primary: '#0059bb',
                'surface-tint': '#005bc0',

                // ---- Status colours (student portal / Stitch screens) ----
                success: '#166534',
                'success-container': '#dcfce7',
                warning: '#92400e',
                'warning-container': '#fef3c7',
            },
            spacing: {
                'stack-sm': '8px',
                'stack-md': '16px',
                'space-xs': '0.25rem',
                'space-sm': '0.5rem',
                'space-md': '1rem',
                'space-lg': '1.5rem',
                'space-xl': '2rem',
                'space-2xl': '3rem',
                'header-height': '72px',
                'container-padding': '32px',
                'sidebar-width': '260px',
                'sidebar-rail': '76px',
                gutter: '24px',
            },
            fontSize: {
                'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
                'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'display-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.015em', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-sm': ['20px', { lineHeight: '28px', letterSpacing: '-0.005em', fontWeight: '600' }],
                'data-mono': ['13px', { lineHeight: '18px', fontWeight: '400' }],
                'code-sm': ['11px', { lineHeight: '16px', fontWeight: '500' }],
                'code-md': ['13px', { lineHeight: '18px', fontWeight: '500' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'label-form': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
                'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
            },
            borderRadius: {
                DEFAULT: '0.125rem',
                lg: '0.25rem',
                xl: '0.5rem',
                full: '0.75rem',
            },
        },
    },

    plugins: [forms],
};